#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 1
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  sym_identifier = 1,
  anon_sym_PROGRAM = 2,
  anon_sym_END_PROGRAM = 3,
  anon_sym_IF = 4,
  anon_sym_THEN = 5,
  anon_sym_ELSIF = 6,
  anon_sym_ELSE = 7,
  anon_sym_END_IF = 8,
  anon_sym_COLON_EQ = 9,
  anon_sym_ACCESS = 10,
  anon_sym_SEMI = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  aux_sym_unary_expression_token1 = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR_STAR = 16,
  anon_sym_STAR = 17,
  anon_sym_SLASH = 18,
  anon_sym_PLUS = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_LT_EQ = 22,
  anon_sym_GT_EQ = 23,
  anon_sym_EQ = 24,
  anon_sym_LT_GT = 25,
  anon_sym_AND = 26,
  anon_sym_XOR = 27,
  anon_sym_OR = 28,
  anon_sym_LBRACK = 29,
  anon_sym_RBRACK = 30,
  anon_sym_DOT = 31,
  aux_sym_dot_operator_token1 = 32,
  sym_number = 33,
  sym_inline_comment = 34,
  sym_block_comment = 35,
  sym_source_file = 36,
  sym__definition = 37,
  sym_program_definition = 38,
  sym_statement = 39,
  sym__control_statement = 40,
  sym_if_statement = 41,
  sym_assignment = 42,
  sym_expression_statement = 43,
  sym__expression = 44,
  sym_unary_expression = 45,
  sym_binary_expression = 46,
  sym_variable = 47,
  sym__index_array = 48,
  sym_index = 49,
  sym_dot_operator = 50,
  sym__literal = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_program_definition_repeat1 = 53,
  aux_sym_if_statement_repeat1 = 54,
  alias_sym_member = 55,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_PROGRAM] = "PROGRAM",
  [anon_sym_END_PROGRAM] = "END_PROGRAM",
  [anon_sym_IF] = "IF",
  [anon_sym_THEN] = "THEN",
  [anon_sym_ELSIF] = "ELSIF",
  [anon_sym_ELSE] = "ELSE",
  [anon_sym_END_IF] = "END_IF",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_ACCESS] = "ACCESS",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_unary_expression_token1] = "unary_expression_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_AND] = "AND",
  [anon_sym_XOR] = "XOR",
  [anon_sym_OR] = "OR",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [aux_sym_dot_operator_token1] = "dot_operator_token1",
  [sym_number] = "number",
  [sym_inline_comment] = "inline_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_program_definition] = "program_definition",
  [sym_statement] = "statement",
  [sym__control_statement] = "_control_statement",
  [sym_if_statement] = "if_statement",
  [sym_assignment] = "assignment",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_variable] = "variable",
  [sym__index_array] = "_index_array",
  [sym_index] = "index",
  [sym_dot_operator] = "dot_operator",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_definition_repeat1] = "program_definition_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [alias_sym_member] = "member",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_PROGRAM] = anon_sym_PROGRAM,
  [anon_sym_END_PROGRAM] = anon_sym_END_PROGRAM,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_THEN] = anon_sym_THEN,
  [anon_sym_ELSIF] = anon_sym_ELSIF,
  [anon_sym_ELSE] = anon_sym_ELSE,
  [anon_sym_END_IF] = anon_sym_END_IF,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_ACCESS] = anon_sym_ACCESS,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_unary_expression_token1] = aux_sym_unary_expression_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_dot_operator_token1] = aux_sym_dot_operator_token1,
  [sym_number] = sym_number,
  [sym_inline_comment] = sym_inline_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_program_definition] = sym_program_definition,
  [sym_statement] = sym_statement,
  [sym__control_statement] = sym__control_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_assignment] = sym_assignment,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_variable] = sym_variable,
  [sym__index_array] = sym__index_array,
  [sym_index] = sym_index,
  [sym_dot_operator] = sym_dot_operator,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_definition_repeat1] = aux_sym_program_definition_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [alias_sym_member] = alias_sym_member,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_THEN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSIF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ACCESS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_unary_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dot_operator_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_program_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__control_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__index_array] = {
    .visible = false,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_dot_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_member] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_Condition = 1,
  field_ElsifCondition = 2,
  field_dim1 = 3,
  field_dim2 = 4,
  field_name = 5,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_Condition] = "Condition",
  [field_ElsifCondition] = "ElsifCondition",
  [field_dim1] = "dim1",
  [field_dim2] = "dim2",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[11] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 3},
  [4] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 1},
  [10] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_dim1, 1, .inherited = true},
    {field_dim2, 1, .inherited = true},
    {field_name, 0},
  [5] =
    {field_dim1, 0},
  [6] =
    {field_dim1, 0},
    {field_dim2, 1},
  [8] =
    {field_Condition, 1},
  [9] =
    {field_ElsifCondition, 0, .inherited = true},
    {field_ElsifCondition, 1, .inherited = true},
  [11] =
    {field_ElsifCondition, 1},
  [12] =
    {field_Condition, 1},
    {field_ElsifCondition, 4, .inherited = true},
};

static TSSymbol ts_alias_sequences[11][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [1] = alias_sym_member,
  },
};

static uint16_t ts_non_terminal_alias_map[] = {
  sym_variable, 2,
    sym_variable,
    alias_sym_member,
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == 'N') ADVANCE(39);
      if (lookahead == '[') ADVANCE(29);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == '+') ADVANCE(8);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'N') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(38);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(2);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(3);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '=') ADVANCE(27);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == '[') ADVANCE(29);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(4);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_unary_expression_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_dot_operator_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_dot_operator_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'E') ADVANCE(2);
      if (lookahead == 'I') ADVANCE(3);
      if (lookahead == 'O') ADVANCE(4);
      if (lookahead == 'P') ADVANCE(5);
      if (lookahead == 'T') ADVANCE(6);
      if (lookahead == 'X') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'C') ADVANCE(8);
      if (lookahead == 'N') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'L') ADVANCE(10);
      if (lookahead == 'N') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'F') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'H') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'O') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'C') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'D') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'S') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_IF);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 14:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(24);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(25);
      if (lookahead == 'I') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == '_') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'G') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 24:
      if (lookahead == 'S') ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_ELSE);
      END_STATE();
    case 26:
      if (lookahead == 'F') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'I') ADVANCE(32);
      if (lookahead == 'P') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'R') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_THEN);
      END_STATE();
    case 30:
      if (lookahead == 'S') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      END_STATE();
    case 32:
      if (lookahead == 'F') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'A') ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_ACCESS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_END_IF);
      END_STATE();
    case 37:
      if (lookahead == 'O') ADVANCE(39);
      END_STATE();
    case 38:
      if (lookahead == 'M') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'G') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PROGRAM);
      END_STATE();
    case 41:
      if (lookahead == 'R') ADVANCE(42);
      END_STATE();
    case 42:
      if (lookahead == 'A') ADVANCE(43);
      END_STATE();
    case 43:
      if (lookahead == 'M') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_END_PROGRAM);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 10},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 10},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 10},
  [66] = {.lex_state = 10},
  [67] = {.lex_state = 10},
  [68] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_PROGRAM] = ACTIONS(1),
    [anon_sym_END_PROGRAM] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_THEN] = ACTIONS(1),
    [anon_sym_ELSIF] = ACTIONS(1),
    [anon_sym_ELSE] = ACTIONS(1),
    [anon_sym_END_IF] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_ACCESS] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_unary_expression_token1] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_dot_operator_token1] = ACTIONS(1),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(68),
    [sym__definition] = STATE(60),
    [sym_program_definition] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(60),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_PROGRAM] = ACTIONS(7),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(3), 1,
      sym_index,
    STATE(5), 1,
      sym__index_array,
    STATE(15), 1,
      sym_dot_operator,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(11), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(9), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [44] = 5,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      sym_index,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(19), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 17,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [80] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(23), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 18,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [111] = 5,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(13), 1,
      sym_dot_operator,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(27), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [146] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(33), 1,
      anon_sym_ELSIF,
    ACTIONS(35), 1,
      anon_sym_ELSE,
    ACTIONS(37), 1,
      anon_sym_END_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    STATE(32), 1,
      sym_variable,
    STATE(63), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [200] = 12,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_IF,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(61), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      sym_number,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    ACTIONS(50), 4,
      anon_sym_END_PROGRAM,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [248] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(69), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 17,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [278] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(33), 1,
      anon_sym_ELSIF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(71), 1,
      anon_sym_ELSE,
    ACTIONS(73), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    STATE(61), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [332] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    ACTIONS(75), 3,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [379] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(79), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [408] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(83), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [437] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(87), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [466] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(10), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    ACTIONS(89), 3,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [513] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(93), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 16,
      anon_sym_THEN,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [542] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(95), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(28), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [587] = 8,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(97), 7,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [624] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(113), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(111), 14,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [651] = 7,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(97), 9,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [686] = 6,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 11,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [719] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(117), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [764] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(119), 1,
      anon_sym_END_PROGRAM,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [809] = 4,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(115), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 13,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [838] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(115), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 14,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [865] = 5,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 13,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [896] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(73), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(27), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [941] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(95), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [986] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(121), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [1031] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(123), 1,
      anon_sym_END_PROGRAM,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [1076] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(127), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 14,
      anon_sym_THEN,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_RBRACK,
  [1103] = 12,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_IF,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(121), 1,
      anon_sym_END_IF,
    STATE(32), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(21), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(37), 4,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym__literal,
    STATE(53), 4,
      sym__control_statement,
      sym_if_statement,
      sym_assignment,
      sym_expression_statement,
  [1148] = 4,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(129), 2,
      anon_sym_COLON_EQ,
      anon_sym_ACCESS,
    ACTIONS(133), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 11,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1176] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(135), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1212] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(139), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1248] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(141), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1284] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1320] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1356] = 9,
    ACTIONS(101), 1,
      anon_sym_STAR_STAR,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(103), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(105), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(107), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(109), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(137), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1392] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(151), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(149), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1411] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(153), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(33), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1438] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(155), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(23), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1465] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(24), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1492] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(25), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1519] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(163), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(161), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1538] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(167), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(165), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1557] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(169), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(36), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1584] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(173), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(171), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1603] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(175), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(35), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1630] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(177), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(19), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1657] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(181), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(179), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1676] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(183), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(17), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1703] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(185), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(20), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1730] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(189), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(187), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1749] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(193), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(191), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1768] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(195), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(34), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1795] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(199), 2,
      aux_sym_unary_expression_token1,
      sym_number,
    ACTIONS(197), 8,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      anon_sym_END_IF,
      anon_sym_LPAREN,
      anon_sym_DASH,
      sym_identifier,
  [1814] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(201), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1841] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 1,
      aux_sym_unary_expression_token1,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(203), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(38), 5,
      sym__expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1868] = 4,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 1,
      anon_sym_PROGRAM,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(59), 3,
      sym__definition,
      sym_program_definition,
      aux_sym_source_file_repeat1,
  [1884] = 4,
    ACTIONS(7), 1,
      anon_sym_PROGRAM,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(59), 3,
      sym__definition,
      sym_program_definition,
      aux_sym_source_file_repeat1,
  [1900] = 5,
    ACTIONS(212), 1,
      anon_sym_ELSIF,
    ACTIONS(214), 1,
      anon_sym_ELSE,
    ACTIONS(216), 1,
      anon_sym_END_IF,
    STATE(62), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1917] = 4,
    ACTIONS(218), 1,
      anon_sym_ELSIF,
    STATE(62), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(221), 2,
      anon_sym_ELSE,
      anon_sym_END_IF,
  [1932] = 5,
    ACTIONS(212), 1,
      anon_sym_ELSIF,
    ACTIONS(223), 1,
      anon_sym_ELSE,
    ACTIONS(225), 1,
      anon_sym_END_IF,
    STATE(62), 1,
      aux_sym_if_statement_repeat1,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1949] = 4,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(229), 1,
      aux_sym_dot_operator_token1,
    STATE(12), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1963] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(231), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [1972] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(233), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [1981] = 2,
    ACTIONS(235), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1989] = 2,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 146,
  [SMALL_STATE(7)] = 200,
  [SMALL_STATE(8)] = 248,
  [SMALL_STATE(9)] = 278,
  [SMALL_STATE(10)] = 332,
  [SMALL_STATE(11)] = 379,
  [SMALL_STATE(12)] = 408,
  [SMALL_STATE(13)] = 437,
  [SMALL_STATE(14)] = 466,
  [SMALL_STATE(15)] = 513,
  [SMALL_STATE(16)] = 542,
  [SMALL_STATE(17)] = 587,
  [SMALL_STATE(18)] = 624,
  [SMALL_STATE(19)] = 651,
  [SMALL_STATE(20)] = 686,
  [SMALL_STATE(21)] = 719,
  [SMALL_STATE(22)] = 764,
  [SMALL_STATE(23)] = 809,
  [SMALL_STATE(24)] = 838,
  [SMALL_STATE(25)] = 865,
  [SMALL_STATE(26)] = 896,
  [SMALL_STATE(27)] = 941,
  [SMALL_STATE(28)] = 986,
  [SMALL_STATE(29)] = 1031,
  [SMALL_STATE(30)] = 1076,
  [SMALL_STATE(31)] = 1103,
  [SMALL_STATE(32)] = 1148,
  [SMALL_STATE(33)] = 1176,
  [SMALL_STATE(34)] = 1212,
  [SMALL_STATE(35)] = 1248,
  [SMALL_STATE(36)] = 1284,
  [SMALL_STATE(37)] = 1320,
  [SMALL_STATE(38)] = 1356,
  [SMALL_STATE(39)] = 1392,
  [SMALL_STATE(40)] = 1411,
  [SMALL_STATE(41)] = 1438,
  [SMALL_STATE(42)] = 1465,
  [SMALL_STATE(43)] = 1492,
  [SMALL_STATE(44)] = 1519,
  [SMALL_STATE(45)] = 1538,
  [SMALL_STATE(46)] = 1557,
  [SMALL_STATE(47)] = 1584,
  [SMALL_STATE(48)] = 1603,
  [SMALL_STATE(49)] = 1630,
  [SMALL_STATE(50)] = 1657,
  [SMALL_STATE(51)] = 1676,
  [SMALL_STATE(52)] = 1703,
  [SMALL_STATE(53)] = 1730,
  [SMALL_STATE(54)] = 1749,
  [SMALL_STATE(55)] = 1768,
  [SMALL_STATE(56)] = 1795,
  [SMALL_STATE(57)] = 1814,
  [SMALL_STATE(58)] = 1841,
  [SMALL_STATE(59)] = 1868,
  [SMALL_STATE(60)] = 1884,
  [SMALL_STATE(61)] = 1900,
  [SMALL_STATE(62)] = 1917,
  [SMALL_STATE(63)] = 1932,
  [SMALL_STATE(64)] = 1949,
  [SMALL_STATE(65)] = 1963,
  [SMALL_STATE(66)] = 1972,
  [SMALL_STATE(67)] = 1981,
  [SMALL_STATE(68)] = 1989,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, .production_id = 2),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, .production_id = 2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__index_array, 1, .production_id = 4),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__index_array, 1, .production_id = 4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, .production_id = 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, .production_id = 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(40),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(58),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(57),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(57),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(37),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__index_array, 2, .production_id = 6),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__index_array, 2, .production_id = 6),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 4, .production_id = 9),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dot_operator, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dot_operator, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dot_operator, 2, .production_id = 5),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dot_operator, 2, .production_id = 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, .production_id = 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, .production_id = 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_statement_repeat1, 3, .production_id = 9),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, .production_id = 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, .production_id = 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, .production_id = 7),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, .production_id = 7),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, .production_id = 10),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, .production_id = 10),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, .production_id = 7),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, .production_id = 7),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, .production_id = 7),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, .production_id = 7),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 7),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 7),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, .production_id = 8), SHIFT_REPEAT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2, .production_id = 8),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, .production_id = 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 3, .production_id = 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_text(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
