#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  sym_identifier = 1,
  anon_sym_PROGRAM = 2,
  anon_sym_END_PROGRAM = 3,
  anon_sym_COLON_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_IF = 6,
  anon_sym_THEN = 7,
  anon_sym_END_IF = 8,
  anon_sym_CASE = 9,
  anon_sym_OF = 10,
  anon_sym_END_CASE = 11,
  anon_sym_FOR = 12,
  anon_sym_DO = 13,
  anon_sym_END_FOR = 14,
  anon_sym_ELSIF = 15,
  anon_sym_ELSE = 16,
  anon_sym_COLON = 17,
  anon_sym_DOT_DOT = 18,
  anon_sym_TO = 19,
  anon_sym_BY = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_NOT = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR_STAR = 25,
  anon_sym_STAR = 26,
  anon_sym_SLASH = 27,
  anon_sym_PLUS = 28,
  anon_sym_LT = 29,
  anon_sym_GT = 30,
  anon_sym_LT_EQ = 31,
  anon_sym_GT_EQ = 32,
  anon_sym_EQ = 33,
  anon_sym_LT_GT = 34,
  anon_sym_AND = 35,
  anon_sym_XOR = 36,
  anon_sym_OR = 37,
  anon_sym_LBRACK = 38,
  anon_sym_COMMA = 39,
  anon_sym_RBRACK = 40,
  anon_sym_DOT = 41,
  aux_sym_structure_member_token1 = 42,
  sym_number = 43,
  sym_inline_comment = 44,
  sym_block_comment = 45,
  sym_source_file = 46,
  sym__definition = 47,
  sym_program_definition = 48,
  sym_statement = 49,
  sym__control_statement = 50,
  sym__loop_statement = 51,
  sym_assignment = 52,
  sym_if_statement = 53,
  sym_case_statement = 54,
  sym_for_statement = 55,
  sym_elseif_clause = 56,
  sym_else_clause = 57,
  sym_case = 58,
  sym_else_case = 59,
  sym_case_value = 60,
  sym_case_range = 61,
  sym_for_range = 62,
  sym__expression = 63,
  sym_expression_assignment = 64,
  sym__parenthesis_expression = 65,
  sym_unary_expression = 66,
  sym_binary_expression = 67,
  sym_variable = 68,
  sym_index = 69,
  sym_structure_member = 70,
  sym__literal = 71,
  aux_sym_source_file_repeat1 = 72,
  aux_sym_program_definition_repeat1 = 73,
  aux_sym_if_statement_repeat1 = 74,
  aux_sym_case_statement_repeat1 = 75,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_PROGRAM] = "PROGRAM",
  [anon_sym_END_PROGRAM] = "END_PROGRAM",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_SEMI] = ";",
  [anon_sym_IF] = "IF",
  [anon_sym_THEN] = "THEN",
  [anon_sym_END_IF] = "END_IF",
  [anon_sym_CASE] = "CASE",
  [anon_sym_OF] = "OF",
  [anon_sym_END_CASE] = "END_CASE",
  [anon_sym_FOR] = "FOR",
  [anon_sym_DO] = "DO",
  [anon_sym_END_FOR] = "END_FOR",
  [anon_sym_ELSIF] = "ELSIF",
  [anon_sym_ELSE] = "ELSE",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_TO] = "TO",
  [anon_sym_BY] = "BY",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_NOT] = "NOT",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ] = "=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_AND] = "AND",
  [anon_sym_XOR] = "XOR",
  [anon_sym_OR] = "OR",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [aux_sym_structure_member_token1] = "structure_member_token1",
  [sym_number] = "number",
  [sym_inline_comment] = "inline_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_program_definition] = "program_definition",
  [sym_statement] = "statement",
  [sym__control_statement] = "_control_statement",
  [sym__loop_statement] = "_loop_statement",
  [sym_assignment] = "assignment",
  [sym_if_statement] = "if_statement",
  [sym_case_statement] = "case_statement",
  [sym_for_statement] = "for_statement",
  [sym_elseif_clause] = "elseif_clause",
  [sym_else_clause] = "else_clause",
  [sym_case] = "case",
  [sym_else_case] = "else_case",
  [sym_case_value] = "case_value",
  [sym_case_range] = "case_range",
  [sym_for_range] = "for_range",
  [sym__expression] = "_expression",
  [sym_expression_assignment] = "expression_assignment",
  [sym__parenthesis_expression] = "_parenthesis_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_variable] = "variable",
  [sym_index] = "index",
  [sym_structure_member] = "structure_member",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_definition_repeat1] = "program_definition_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_case_statement_repeat1] = "case_statement_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_PROGRAM] = anon_sym_PROGRAM,
  [anon_sym_END_PROGRAM] = anon_sym_END_PROGRAM,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_THEN] = anon_sym_THEN,
  [anon_sym_END_IF] = anon_sym_END_IF,
  [anon_sym_CASE] = anon_sym_CASE,
  [anon_sym_OF] = anon_sym_OF,
  [anon_sym_END_CASE] = anon_sym_END_CASE,
  [anon_sym_FOR] = anon_sym_FOR,
  [anon_sym_DO] = anon_sym_DO,
  [anon_sym_END_FOR] = anon_sym_END_FOR,
  [anon_sym_ELSIF] = anon_sym_ELSIF,
  [anon_sym_ELSE] = anon_sym_ELSE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_TO] = anon_sym_TO,
  [anon_sym_BY] = anon_sym_BY,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_structure_member_token1] = aux_sym_structure_member_token1,
  [sym_number] = sym_number,
  [sym_inline_comment] = sym_inline_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_program_definition] = sym_program_definition,
  [sym_statement] = sym_statement,
  [sym__control_statement] = sym__control_statement,
  [sym__loop_statement] = sym__loop_statement,
  [sym_assignment] = sym_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_case_statement] = sym_case_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_elseif_clause] = sym_elseif_clause,
  [sym_else_clause] = sym_else_clause,
  [sym_case] = sym_case,
  [sym_else_case] = sym_else_case,
  [sym_case_value] = sym_case_value,
  [sym_case_range] = sym_case_range,
  [sym_for_range] = sym_for_range,
  [sym__expression] = sym__expression,
  [sym_expression_assignment] = sym_expression_assignment,
  [sym__parenthesis_expression] = sym__parenthesis_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_variable] = sym_variable,
  [sym_index] = sym_index,
  [sym_structure_member] = sym_structure_member,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_definition_repeat1] = aux_sym_program_definition_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_case_statement_repeat1] = aux_sym_case_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_THEN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CASE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_CASE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSIF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_structure_member_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_program_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__control_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__loop_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_case_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_else_case] = {
    .visible = true,
    .named = true,
  },
  [sym_case_value] = {
    .visible = true,
    .named = true,
  },
  [sym_case_range] = {
    .visible = true,
    .named = true,
  },
  [sym_for_range] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__parenthesis_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_structure_member] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_CaseControlValue = 1,
  field_Condition = 2,
  field_Dim1 = 3,
  field_Dim2 = 4,
  field_ElsifCondition = 5,
  field_LowerLimit = 6,
  field_Name = 7,
  field_ProgramName = 8,
  field_UpperLimit = 9,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_CaseControlValue] = "CaseControlValue",
  [field_Condition] = "Condition",
  [field_Dim1] = "Dim1",
  [field_Dim2] = "Dim2",
  [field_ElsifCondition] = "ElsifCondition",
  [field_LowerLimit] = "LowerLimit",
  [field_Name] = "Name",
  [field_ProgramName] = "ProgramName",
  [field_UpperLimit] = "UpperLimit",
};

static const TSFieldMapSlice ts_field_map_slices[9] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_ProgramName, 1},
  [1] =
    {field_Name, 0},
  [2] =
    {field_Condition, 1},
  [3] =
    {field_CaseControlValue, 1},
  [4] =
    {field_Dim1, 1},
  [5] =
    {field_ElsifCondition, 1},
  [6] =
    {field_LowerLimit, 0},
    {field_UpperLimit, 2},
  [8] =
    {field_Dim1, 1},
    {field_Dim2, 3},
};

static TSSymbol ts_alias_sequences[9][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(41);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(6);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '>') ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(16);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_structure_member_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_structure_member_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_structure_member_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_structure_member_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'B') ADVANCE(2);
      if (lookahead == 'C') ADVANCE(3);
      if (lookahead == 'D') ADVANCE(4);
      if (lookahead == 'E') ADVANCE(5);
      if (lookahead == 'F') ADVANCE(6);
      if (lookahead == 'I') ADVANCE(7);
      if (lookahead == 'N') ADVANCE(8);
      if (lookahead == 'O') ADVANCE(9);
      if (lookahead == 'P') ADVANCE(10);
      if (lookahead == 'T') ADVANCE(11);
      if (lookahead == 'X') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'N') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'Y') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'O') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'L') ADVANCE(17);
      if (lookahead == 'N') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'O') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'F') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'F') ADVANCE(22);
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'H') ADVANCE(25);
      if (lookahead == 'O') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'D') ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BY);
      END_STATE();
    case 15:
      if (lookahead == 'S') ADVANCE(29);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DO);
      END_STATE();
    case 17:
      if (lookahead == 'S') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'D') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'R') ADVANCE(32);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_IF);
      END_STATE();
    case 21:
      if (lookahead == 'T') ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_OF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(35);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_TO);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(37);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(38);
      if (lookahead == 'I') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == '_') ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_FOR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 34:
      if (lookahead == 'G') ADVANCE(41);
      END_STATE();
    case 35:
      if (lookahead == 'N') ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_CASE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_ELSE);
      END_STATE();
    case 39:
      if (lookahead == 'F') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 'C') ADVANCE(44);
      if (lookahead == 'F') ADVANCE(45);
      if (lookahead == 'I') ADVANCE(46);
      if (lookahead == 'P') ADVANCE(47);
      END_STATE();
    case 41:
      if (lookahead == 'R') ADVANCE(48);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_THEN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      END_STATE();
    case 44:
      if (lookahead == 'A') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'O') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'F') ADVANCE(51);
      END_STATE();
    case 47:
      if (lookahead == 'R') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'A') ADVANCE(53);
      END_STATE();
    case 49:
      if (lookahead == 'S') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 'R') ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_END_IF);
      END_STATE();
    case 52:
      if (lookahead == 'O') ADVANCE(56);
      END_STATE();
    case 53:
      if (lookahead == 'M') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_END_FOR);
      END_STATE();
    case 56:
      if (lookahead == 'G') ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_PROGRAM);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_END_CASE);
      END_STATE();
    case 59:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 60:
      if (lookahead == 'A') ADVANCE(61);
      END_STATE();
    case 61:
      if (lookahead == 'M') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_END_PROGRAM);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_PROGRAM] = ACTIONS(1),
    [anon_sym_END_PROGRAM] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_THEN] = ACTIONS(1),
    [anon_sym_END_IF] = ACTIONS(1),
    [anon_sym_CASE] = ACTIONS(1),
    [anon_sym_OF] = ACTIONS(1),
    [anon_sym_END_CASE] = ACTIONS(1),
    [anon_sym_FOR] = ACTIONS(1),
    [anon_sym_DO] = ACTIONS(1),
    [anon_sym_END_FOR] = ACTIONS(1),
    [anon_sym_ELSIF] = ACTIONS(1),
    [anon_sym_ELSE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_TO] = ACTIONS(1),
    [anon_sym_BY] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_structure_member_token1] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym__definition] = STATE(87),
    [sym_program_definition] = STATE(92),
    [aux_sym_source_file_repeat1] = STATE(87),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_PROGRAM] = ACTIONS(7),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(3), 1,
      sym_index,
    STATE(8), 1,
      sym_structure_member,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(11), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(9), 19,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [44] = 5,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(6), 1,
      sym_structure_member,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(19), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 19,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [82] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(23), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 20,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [115] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(27), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 20,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
  [148] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(31), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(29), 19,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [180] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(35), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 19,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [212] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(19), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 19,
      anon_sym_COLON_EQ,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [244] = 6,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(45), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 15,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [281] = 4,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(45), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 17,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [314] = 7,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 13,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [353] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(53), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 18,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [384] = 8,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(37), 11,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [425] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(59), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 18,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [456] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(45), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 18,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [487] = 5,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(45), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 17,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [522] = 3,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(63), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 18,
      anon_sym_SEMI,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR_STAR,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ,
      anon_sym_LT_GT,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [553] = 12,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_IF,
    ACTIONS(73), 1,
      anon_sym_CASE,
    ACTIONS(76), 1,
      anon_sym_FOR,
    ACTIONS(79), 1,
      sym_number,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
    ACTIONS(68), 6,
      anon_sym_END_PROGRAM,
      anon_sym_END_IF,
      anon_sym_END_CASE,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
  [600] = 15,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(85), 1,
      anon_sym_END_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(91), 1,
      anon_sym_ELSIF,
    ACTIONS(93), 1,
      anon_sym_ELSE,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    STATE(101), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(20), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(84), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [652] = 15,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(91), 1,
      anon_sym_ELSIF,
    ACTIONS(93), 1,
      anon_sym_ELSE,
    ACTIONS(95), 1,
      anon_sym_END_IF,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    STATE(102), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(83), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [704] = 10,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(97), 1,
      anon_sym_DO,
    ACTIONS(99), 1,
      anon_sym_BY,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [743] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    ACTIONS(103), 3,
      anon_sym_END_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [784] = 10,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [823] = 12,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(114), 1,
      sym_number,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(112), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(26), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [866] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    ACTIONS(116), 3,
      anon_sym_END_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [907] = 12,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(123), 1,
      sym_number,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(121), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [950] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(125), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [986] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(127), 1,
      anon_sym_TO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1022] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1058] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(131), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1094] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(133), 1,
      anon_sym_DO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1130] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1166] = 9,
    ACTIONS(41), 1,
      anon_sym_STAR_STAR,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(43), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_EQ,
      anon_sym_LT_GT,
    ACTIONS(101), 3,
      anon_sym_AND,
      anon_sym_XOR,
      anon_sym_OR,
  [1202] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(139), 1,
      anon_sym_END_IF,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(36), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1241] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(141), 1,
      anon_sym_END_FOR,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1280] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(143), 1,
      anon_sym_END_IF,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1319] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(145), 1,
      anon_sym_END_CASE,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(39), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1358] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(147), 1,
      anon_sym_END_PROGRAM,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1397] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(149), 1,
      anon_sym_END_CASE,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1436] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(151), 1,
      anon_sym_END_PROGRAM,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1475] = 11,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      anon_sym_IF,
    ACTIONS(87), 1,
      anon_sym_CASE,
    ACTIONS(89), 1,
      anon_sym_FOR,
    ACTIONS(153), 1,
      anon_sym_END_FOR,
    STATE(66), 1,
      sym_for_statement,
    STATE(96), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(70), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(65), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [1514] = 4,
    ACTIONS(157), 1,
      anon_sym_SEMI,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(155), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1537] = 4,
    ACTIONS(163), 1,
      anon_sym_SEMI,
    ACTIONS(165), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(161), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1560] = 4,
    ACTIONS(169), 1,
      anon_sym_SEMI,
    ACTIONS(171), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(167), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1583] = 4,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    ACTIONS(177), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(173), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1606] = 4,
    ACTIONS(181), 1,
      anon_sym_SEMI,
    ACTIONS(183), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(179), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1629] = 4,
    ACTIONS(187), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(185), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1652] = 4,
    ACTIONS(193), 1,
      anon_sym_SEMI,
    ACTIONS(195), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(191), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1675] = 4,
    ACTIONS(199), 1,
      anon_sym_SEMI,
    ACTIONS(201), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(197), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1698] = 4,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    ACTIONS(207), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(203), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1721] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(23), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1749] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(28), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1777] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(27), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1805] = 3,
    ACTIONS(219), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(217), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1825] = 3,
    ACTIONS(223), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(221), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1845] = 3,
    ACTIONS(165), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(161), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1865] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(21), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1893] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(32), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1921] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(13), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1949] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(11), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [1977] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(9), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2005] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(10), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2033] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(15), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2061] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(16), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2089] = 3,
    ACTIONS(227), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(225), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2109] = 3,
    ACTIONS(231), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(229), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2129] = 3,
    ACTIONS(207), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(203), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2149] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(31), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2177] = 3,
    ACTIONS(195), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(191), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2197] = 3,
    ACTIONS(235), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(233), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2217] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(29), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2245] = 3,
    ACTIONS(177), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(173), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2265] = 3,
    ACTIONS(171), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(167), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2285] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(33), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2313] = 3,
    ACTIONS(239), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(237), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2333] = 3,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(155), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2353] = 3,
    ACTIONS(243), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(241), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [2373] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(14), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2401] = 7,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
    ACTIONS(211), 1,
      anon_sym_NOT,
    ACTIONS(213), 1,
      anon_sym_DASH,
    ACTIONS(215), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(30), 6,
      sym__expression,
      sym__parenthesis_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_variable,
      sym__literal,
  [2429] = 9,
    ACTIONS(245), 1,
      sym_identifier,
    ACTIONS(247), 1,
      anon_sym_END_CASE,
    ACTIONS(249), 1,
      anon_sym_ELSE,
    ACTIONS(251), 1,
      sym_number,
    STATE(94), 1,
      sym_case_range,
    STATE(95), 1,
      sym_else_case,
    STATE(107), 1,
      sym_case_value,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(82), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [2459] = 9,
    ACTIONS(245), 1,
      sym_identifier,
    ACTIONS(249), 1,
      anon_sym_ELSE,
    ACTIONS(251), 1,
      sym_number,
    ACTIONS(253), 1,
      anon_sym_END_CASE,
    STATE(94), 1,
      sym_case_range,
    STATE(107), 1,
      sym_case_value,
    STATE(109), 1,
      sym_else_case,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(80), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [2489] = 7,
    ACTIONS(255), 1,
      sym_identifier,
    ACTIONS(260), 1,
      sym_number,
    STATE(94), 1,
      sym_case_range,
    STATE(107), 1,
      sym_case_value,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(258), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(82), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [2514] = 6,
    ACTIONS(263), 1,
      anon_sym_END_IF,
    ACTIONS(265), 1,
      anon_sym_ELSIF,
    ACTIONS(267), 1,
      anon_sym_ELSE,
    STATE(98), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(86), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [2535] = 6,
    ACTIONS(265), 1,
      anon_sym_ELSIF,
    ACTIONS(267), 1,
      anon_sym_ELSE,
    ACTIONS(269), 1,
      anon_sym_END_IF,
    STATE(102), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(86), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [2556] = 5,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    ACTIONS(273), 1,
      anon_sym_PROGRAM,
    STATE(92), 1,
      sym_program_definition,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(85), 2,
      sym__definition,
      aux_sym_source_file_repeat1,
  [2574] = 4,
    ACTIONS(278), 1,
      anon_sym_ELSIF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(276), 2,
      anon_sym_END_IF,
      anon_sym_ELSE,
    STATE(86), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [2590] = 5,
    ACTIONS(7), 1,
      anon_sym_PROGRAM,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
    STATE(92), 1,
      sym_program_definition,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(85), 2,
      sym__definition,
      aux_sym_source_file_repeat1,
  [2608] = 5,
    ACTIONS(283), 1,
      sym_identifier,
    STATE(104), 1,
      sym_for_range,
    STATE(105), 1,
      sym_expression_assignment,
    STATE(106), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2625] = 4,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(285), 1,
      aux_sym_structure_member_token1,
    STATE(7), 1,
      sym_variable,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2639] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(287), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [2648] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(289), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [2657] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(291), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [2666] = 3,
    ACTIONS(293), 1,
      anon_sym_COLON,
    ACTIONS(295), 1,
      anon_sym_DOT_DOT,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2677] = 2,
    ACTIONS(293), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2685] = 2,
    ACTIONS(297), 1,
      anon_sym_END_CASE,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2693] = 2,
    ACTIONS(299), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2701] = 2,
    ACTIONS(301), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2709] = 2,
    ACTIONS(303), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2717] = 2,
    ACTIONS(305), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2725] = 2,
    ACTIONS(307), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2733] = 2,
    ACTIONS(269), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2741] = 2,
    ACTIONS(263), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2749] = 2,
    ACTIONS(309), 1,
      anon_sym_OF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2757] = 2,
    ACTIONS(311), 1,
      anon_sym_DO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2765] = 2,
    ACTIONS(313), 1,
      anon_sym_TO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2773] = 2,
    ACTIONS(315), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2781] = 2,
    ACTIONS(317), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2789] = 2,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2797] = 2,
    ACTIONS(321), 1,
      anon_sym_END_CASE,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [2805] = 2,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 244,
  [SMALL_STATE(10)] = 281,
  [SMALL_STATE(11)] = 314,
  [SMALL_STATE(12)] = 353,
  [SMALL_STATE(13)] = 384,
  [SMALL_STATE(14)] = 425,
  [SMALL_STATE(15)] = 456,
  [SMALL_STATE(16)] = 487,
  [SMALL_STATE(17)] = 522,
  [SMALL_STATE(18)] = 553,
  [SMALL_STATE(19)] = 600,
  [SMALL_STATE(20)] = 652,
  [SMALL_STATE(21)] = 704,
  [SMALL_STATE(22)] = 743,
  [SMALL_STATE(23)] = 784,
  [SMALL_STATE(24)] = 823,
  [SMALL_STATE(25)] = 866,
  [SMALL_STATE(26)] = 907,
  [SMALL_STATE(27)] = 950,
  [SMALL_STATE(28)] = 986,
  [SMALL_STATE(29)] = 1022,
  [SMALL_STATE(30)] = 1058,
  [SMALL_STATE(31)] = 1094,
  [SMALL_STATE(32)] = 1130,
  [SMALL_STATE(33)] = 1166,
  [SMALL_STATE(34)] = 1202,
  [SMALL_STATE(35)] = 1241,
  [SMALL_STATE(36)] = 1280,
  [SMALL_STATE(37)] = 1319,
  [SMALL_STATE(38)] = 1358,
  [SMALL_STATE(39)] = 1397,
  [SMALL_STATE(40)] = 1436,
  [SMALL_STATE(41)] = 1475,
  [SMALL_STATE(42)] = 1514,
  [SMALL_STATE(43)] = 1537,
  [SMALL_STATE(44)] = 1560,
  [SMALL_STATE(45)] = 1583,
  [SMALL_STATE(46)] = 1606,
  [SMALL_STATE(47)] = 1629,
  [SMALL_STATE(48)] = 1652,
  [SMALL_STATE(49)] = 1675,
  [SMALL_STATE(50)] = 1698,
  [SMALL_STATE(51)] = 1721,
  [SMALL_STATE(52)] = 1749,
  [SMALL_STATE(53)] = 1777,
  [SMALL_STATE(54)] = 1805,
  [SMALL_STATE(55)] = 1825,
  [SMALL_STATE(56)] = 1845,
  [SMALL_STATE(57)] = 1865,
  [SMALL_STATE(58)] = 1893,
  [SMALL_STATE(59)] = 1921,
  [SMALL_STATE(60)] = 1949,
  [SMALL_STATE(61)] = 1977,
  [SMALL_STATE(62)] = 2005,
  [SMALL_STATE(63)] = 2033,
  [SMALL_STATE(64)] = 2061,
  [SMALL_STATE(65)] = 2089,
  [SMALL_STATE(66)] = 2109,
  [SMALL_STATE(67)] = 2129,
  [SMALL_STATE(68)] = 2149,
  [SMALL_STATE(69)] = 2177,
  [SMALL_STATE(70)] = 2197,
  [SMALL_STATE(71)] = 2217,
  [SMALL_STATE(72)] = 2245,
  [SMALL_STATE(73)] = 2265,
  [SMALL_STATE(74)] = 2285,
  [SMALL_STATE(75)] = 2313,
  [SMALL_STATE(76)] = 2333,
  [SMALL_STATE(77)] = 2353,
  [SMALL_STATE(78)] = 2373,
  [SMALL_STATE(79)] = 2401,
  [SMALL_STATE(80)] = 2429,
  [SMALL_STATE(81)] = 2459,
  [SMALL_STATE(82)] = 2489,
  [SMALL_STATE(83)] = 2514,
  [SMALL_STATE(84)] = 2535,
  [SMALL_STATE(85)] = 2556,
  [SMALL_STATE(86)] = 2574,
  [SMALL_STATE(87)] = 2590,
  [SMALL_STATE(88)] = 2608,
  [SMALL_STATE(89)] = 2625,
  [SMALL_STATE(90)] = 2639,
  [SMALL_STATE(91)] = 2648,
  [SMALL_STATE(92)] = 2657,
  [SMALL_STATE(93)] = 2666,
  [SMALL_STATE(94)] = 2677,
  [SMALL_STATE(95)] = 2685,
  [SMALL_STATE(96)] = 2693,
  [SMALL_STATE(97)] = 2701,
  [SMALL_STATE(98)] = 2709,
  [SMALL_STATE(99)] = 2717,
  [SMALL_STATE(100)] = 2725,
  [SMALL_STATE(101)] = 2733,
  [SMALL_STATE(102)] = 2741,
  [SMALL_STATE(103)] = 2749,
  [SMALL_STATE(104)] = 2757,
  [SMALL_STATE(105)] = 2765,
  [SMALL_STATE(106)] = 2773,
  [SMALL_STATE(107)] = 2781,
  [SMALL_STATE(108)] = 2789,
  [SMALL_STATE(109)] = 2797,
  [SMALL_STATE(110)] = 2805,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, .production_id = 2),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, .production_id = 2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, .production_id = 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, .production_id = 2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, .production_id = 5),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3, .production_id = 5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 5, .production_id = 8),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 5, .production_id = 8),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, .production_id = 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, .production_id = 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure_member, 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure_member, 2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parenthesis_expression, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__parenthesis_expression, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(79),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(97),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(88),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_range, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_clause, 4, .production_id = 6),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_case, 2), SHIFT(2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_clause, 3, .production_id = 6),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_case, 3), SHIFT(2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_assignment, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_range, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_clause, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_clause, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_case, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_case, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, .production_id = 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, .production_id = 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 6, .production_id = 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 6, .production_id = 4),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 5),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 5),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, .production_id = 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, .production_id = 3),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 4, .production_id = 4),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 4, .production_id = 4),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 5, .production_id = 4),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 5, .production_id = 4),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 4),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, .production_id = 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, .production_id = 3),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, .production_id = 3),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, .production_id = 3),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 7, .production_id = 4),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 7, .production_id = 4),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__loop_statement, 1),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__loop_statement, 1),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__control_statement, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__control_statement, 1),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 6),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 6),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [255] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_case_statement_repeat1, 2), SHIFT_REPEAT(94),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_case_statement_repeat1, 2),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_case_statement_repeat1, 2), SHIFT_REPEAT(93),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(53),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 3, .production_id = 1),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, .production_id = 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_value, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_range, 3, .production_id = 7),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [319] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_text(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
