#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  sym_identifier = 1,
  anon_sym_PROGRAM = 2,
  anon_sym_END_PROGRAM = 3,
  anon_sym_COLON_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_IF = 6,
  anon_sym_THEN = 7,
  anon_sym_END_IF = 8,
  anon_sym_CASE = 9,
  anon_sym_OF = 10,
  anon_sym_END_CASE = 11,
  anon_sym_FOR = 12,
  anon_sym_DO = 13,
  anon_sym_END_FOR = 14,
  anon_sym_ELSIF = 15,
  anon_sym_ELSE = 16,
  anon_sym_COLON = 17,
  anon_sym_DOT_DOT = 18,
  anon_sym_TO = 19,
  anon_sym_BY = 20,
  sym_number = 21,
  sym_inline_comment = 22,
  sym_block_comment = 23,
  sym_source_file = 24,
  sym__definition = 25,
  sym_program_definition = 26,
  sym_statement = 27,
  sym__control_statement = 28,
  sym__loop_statement = 29,
  sym_assignment = 30,
  sym_if_statement = 31,
  sym_case_statement = 32,
  sym_for_statement = 33,
  sym_elseif_clause = 34,
  sym_else_clause = 35,
  sym_case = 36,
  sym_else_case = 37,
  sym_case_value = 38,
  sym_case_range = 39,
  sym_for_range = 40,
  sym__expression = 41,
  sym_expression_assignment = 42,
  sym__literal = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_program_definition_repeat1 = 45,
  aux_sym_if_statement_repeat1 = 46,
  aux_sym_case_statement_repeat1 = 47,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_PROGRAM] = "PROGRAM",
  [anon_sym_END_PROGRAM] = "END_PROGRAM",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_SEMI] = ";",
  [anon_sym_IF] = "IF",
  [anon_sym_THEN] = "THEN",
  [anon_sym_END_IF] = "END_IF",
  [anon_sym_CASE] = "CASE",
  [anon_sym_OF] = "OF",
  [anon_sym_END_CASE] = "END_CASE",
  [anon_sym_FOR] = "FOR",
  [anon_sym_DO] = "DO",
  [anon_sym_END_FOR] = "END_FOR",
  [anon_sym_ELSIF] = "ELSIF",
  [anon_sym_ELSE] = "ELSE",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_TO] = "TO",
  [anon_sym_BY] = "BY",
  [sym_number] = "number",
  [sym_inline_comment] = "inline_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_program_definition] = "program_definition",
  [sym_statement] = "statement",
  [sym__control_statement] = "_control_statement",
  [sym__loop_statement] = "_loop_statement",
  [sym_assignment] = "assignment",
  [sym_if_statement] = "if_statement",
  [sym_case_statement] = "case_statement",
  [sym_for_statement] = "for_statement",
  [sym_elseif_clause] = "elseif_clause",
  [sym_else_clause] = "else_clause",
  [sym_case] = "case",
  [sym_else_case] = "else_case",
  [sym_case_value] = "case_value",
  [sym_case_range] = "case_range",
  [sym_for_range] = "for_range",
  [sym__expression] = "_expression",
  [sym_expression_assignment] = "expression_assignment",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_definition_repeat1] = "program_definition_repeat1",
  [aux_sym_if_statement_repeat1] = "if_statement_repeat1",
  [aux_sym_case_statement_repeat1] = "case_statement_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_PROGRAM] = anon_sym_PROGRAM,
  [anon_sym_END_PROGRAM] = anon_sym_END_PROGRAM,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_THEN] = anon_sym_THEN,
  [anon_sym_END_IF] = anon_sym_END_IF,
  [anon_sym_CASE] = anon_sym_CASE,
  [anon_sym_OF] = anon_sym_OF,
  [anon_sym_END_CASE] = anon_sym_END_CASE,
  [anon_sym_FOR] = anon_sym_FOR,
  [anon_sym_DO] = anon_sym_DO,
  [anon_sym_END_FOR] = anon_sym_END_FOR,
  [anon_sym_ELSIF] = anon_sym_ELSIF,
  [anon_sym_ELSE] = anon_sym_ELSE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_TO] = anon_sym_TO,
  [anon_sym_BY] = anon_sym_BY,
  [sym_number] = sym_number,
  [sym_inline_comment] = sym_inline_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_program_definition] = sym_program_definition,
  [sym_statement] = sym_statement,
  [sym__control_statement] = sym__control_statement,
  [sym__loop_statement] = sym__loop_statement,
  [sym_assignment] = sym_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_case_statement] = sym_case_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_elseif_clause] = sym_elseif_clause,
  [sym_else_clause] = sym_else_clause,
  [sym_case] = sym_case,
  [sym_else_case] = sym_else_case,
  [sym_case_value] = sym_case_value,
  [sym_case_range] = sym_case_range,
  [sym_for_range] = sym_for_range,
  [sym__expression] = sym__expression,
  [sym_expression_assignment] = sym_expression_assignment,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_definition_repeat1] = aux_sym_program_definition_repeat1,
  [aux_sym_if_statement_repeat1] = aux_sym_if_statement_repeat1,
  [aux_sym_case_statement_repeat1] = aux_sym_case_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_THEN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CASE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_CASE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSIF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ELSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BY] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_program_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__control_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__loop_statement] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_case_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_else_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_case] = {
    .visible = true,
    .named = true,
  },
  [sym_else_case] = {
    .visible = true,
    .named = true,
  },
  [sym_case_value] = {
    .visible = true,
    .named = true,
  },
  [sym_case_range] = {
    .visible = true,
    .named = true,
  },
  [sym_for_range] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_expression_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_case_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_CaseControlValue = 1,
  field_Condition = 2,
  field_ElsifCondition = 3,
  field_LowerLimit = 4,
  field_ProgramName = 5,
  field_UpperLimit = 6,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_CaseControlValue] = "CaseControlValue",
  [field_Condition] = "Condition",
  [field_ElsifCondition] = "ElsifCondition",
  [field_LowerLimit] = "LowerLimit",
  [field_ProgramName] = "ProgramName",
  [field_UpperLimit] = "UpperLimit",
};

static const TSFieldMapSlice ts_field_map_slices[6] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_ProgramName, 1},
  [1] =
    {field_Condition, 1},
  [2] =
    {field_CaseControlValue, 1},
  [3] =
    {field_ElsifCondition, 1},
  [4] =
    {field_LowerLimit, 0},
    {field_UpperLimit, 2},
};

static TSSymbol ts_alias_sequences[6][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'C') ADVANCE(2);
      if (lookahead == 'D') ADVANCE(3);
      if (lookahead == 'E') ADVANCE(4);
      if (lookahead == 'F') ADVANCE(5);
      if (lookahead == 'I') ADVANCE(6);
      if (lookahead == 'O') ADVANCE(7);
      if (lookahead == 'P') ADVANCE(8);
      if (lookahead == 'T') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'Y') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'O') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'L') ADVANCE(13);
      if (lookahead == 'N') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'O') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'F') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'F') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'H') ADVANCE(19);
      if (lookahead == 'O') ADVANCE(20);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BY);
      END_STATE();
    case 11:
      if (lookahead == 'S') ADVANCE(21);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DO);
      END_STATE();
    case 13:
      if (lookahead == 'S') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(24);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_IF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_OF);
      END_STATE();
    case 18:
      if (lookahead == 'O') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_TO);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(28);
      if (lookahead == 'I') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == '_') ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_FOR);
      END_STATE();
    case 25:
      if (lookahead == 'G') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'N') ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_CASE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_ELSE);
      END_STATE();
    case 29:
      if (lookahead == 'F') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'C') ADVANCE(34);
      if (lookahead == 'F') ADVANCE(35);
      if (lookahead == 'I') ADVANCE(36);
      if (lookahead == 'P') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 'R') ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_THEN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_ELSIF);
      END_STATE();
    case 34:
      if (lookahead == 'A') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'O') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'F') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'R') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'A') ADVANCE(43);
      END_STATE();
    case 39:
      if (lookahead == 'S') ADVANCE(44);
      END_STATE();
    case 40:
      if (lookahead == 'R') ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_END_IF);
      END_STATE();
    case 42:
      if (lookahead == 'O') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'M') ADVANCE(47);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_END_FOR);
      END_STATE();
    case 46:
      if (lookahead == 'G') ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PROGRAM);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_END_CASE);
      END_STATE();
    case 49:
      if (lookahead == 'R') ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == 'A') ADVANCE(51);
      END_STATE();
    case 51:
      if (lookahead == 'M') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_END_PROGRAM);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_PROGRAM] = ACTIONS(1),
    [anon_sym_END_PROGRAM] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_THEN] = ACTIONS(1),
    [anon_sym_END_IF] = ACTIONS(1),
    [anon_sym_CASE] = ACTIONS(1),
    [anon_sym_OF] = ACTIONS(1),
    [anon_sym_END_CASE] = ACTIONS(1),
    [anon_sym_FOR] = ACTIONS(1),
    [anon_sym_DO] = ACTIONS(1),
    [anon_sym_END_FOR] = ACTIONS(1),
    [anon_sym_ELSIF] = ACTIONS(1),
    [anon_sym_ELSE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_TO] = ACTIONS(1),
    [anon_sym_BY] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(78),
    [sym__definition] = STATE(44),
    [sym_program_definition] = STATE(58),
    [aux_sym_source_file_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_PROGRAM] = ACTIONS(7),
    [sym_inline_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(14), 1,
      anon_sym_IF,
    ACTIONS(17), 1,
      anon_sym_CASE,
    ACTIONS(20), 1,
      anon_sym_FOR,
    ACTIONS(23), 1,
      sym_number,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
    ACTIONS(12), 6,
      anon_sym_END_PROGRAM,
      anon_sym_END_IF,
      anon_sym_END_CASE,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
  [44] = 14,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(29), 1,
      anon_sym_END_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(35), 1,
      anon_sym_ELSIF,
    ACTIONS(37), 1,
      anon_sym_ELSE,
    STATE(33), 1,
      sym_for_statement,
    STATE(64), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(43), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [93] = 14,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(35), 1,
      anon_sym_ELSIF,
    ACTIONS(37), 1,
      anon_sym_ELSE,
    ACTIONS(39), 1,
      anon_sym_END_IF,
    STATE(33), 1,
      sym_for_statement,
    STATE(67), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(42), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [142] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    ACTIONS(41), 3,
      anon_sym_END_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [180] = 11,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_number,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(46), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [220] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(5), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    ACTIONS(50), 3,
      anon_sym_END_IF,
      anon_sym_ELSIF,
      anon_sym_ELSE,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [258] = 11,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_number,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(55), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(6), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [298] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(59), 1,
      anon_sym_END_PROGRAM,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(16), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [334] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(61), 1,
      anon_sym_END_CASE,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [370] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(63), 1,
      anon_sym_END_IF,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [406] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(65), 1,
      anon_sym_END_FOR,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [442] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(67), 1,
      anon_sym_END_CASE,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(10), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [478] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(69), 1,
      anon_sym_END_IF,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(11), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [514] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(71), 1,
      anon_sym_END_FOR,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(12), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [550] = 10,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_IF,
    ACTIONS(31), 1,
      anon_sym_CASE,
    ACTIONS(33), 1,
      anon_sym_FOR,
    ACTIONS(73), 1,
      anon_sym_END_PROGRAM,
    STATE(33), 1,
      sym_for_statement,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(2), 2,
      sym_statement,
      aux_sym_program_definition_repeat1,
    STATE(30), 2,
      sym_if_statement,
      sym_case_statement,
    STATE(37), 3,
      sym__control_statement,
      sym__loop_statement,
      sym_assignment,
  [586] = 4,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    ACTIONS(79), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(75), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [609] = 4,
    ACTIONS(83), 1,
      anon_sym_SEMI,
    ACTIONS(85), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(81), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [632] = 4,
    ACTIONS(89), 1,
      anon_sym_SEMI,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(87), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [655] = 4,
    ACTIONS(95), 1,
      anon_sym_SEMI,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(93), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [678] = 4,
    ACTIONS(101), 1,
      anon_sym_SEMI,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [701] = 4,
    ACTIONS(107), 1,
      anon_sym_SEMI,
    ACTIONS(109), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(105), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [724] = 4,
    ACTIONS(113), 1,
      anon_sym_SEMI,
    ACTIONS(115), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(111), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [747] = 4,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    ACTIONS(121), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(117), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [770] = 4,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(123), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [793] = 3,
    ACTIONS(109), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(105), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [813] = 3,
    ACTIONS(115), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(111), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [833] = 3,
    ACTIONS(131), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(129), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [853] = 3,
    ACTIONS(135), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(133), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [873] = 3,
    ACTIONS(139), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(137), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [893] = 3,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(87), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [913] = 3,
    ACTIONS(143), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(141), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [933] = 3,
    ACTIONS(147), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(145), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [953] = 3,
    ACTIONS(97), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(93), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [973] = 3,
    ACTIONS(103), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(99), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [993] = 3,
    ACTIONS(79), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(75), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1013] = 3,
    ACTIONS(151), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(149), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1033] = 3,
    ACTIONS(155), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(153), 10,
      anon_sym_END_PROGRAM,
      anon_sym_IF,
      anon_sym_END_IF,
      anon_sym_CASE,
      anon_sym_END_CASE,
      anon_sym_FOR,
      anon_sym_END_FOR,
      anon_sym_ELSIF,
      anon_sym_ELSE,
      sym_identifier,
  [1053] = 9,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_END_CASE,
    ACTIONS(161), 1,
      anon_sym_ELSE,
    ACTIONS(163), 1,
      sym_number,
    STATE(62), 1,
      sym_case_range,
    STATE(75), 1,
      sym_case_value,
    STATE(76), 1,
      sym_else_case,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(40), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [1083] = 9,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(161), 1,
      anon_sym_ELSE,
    ACTIONS(163), 1,
      sym_number,
    ACTIONS(165), 1,
      anon_sym_END_CASE,
    STATE(60), 1,
      sym_else_case,
    STATE(62), 1,
      sym_case_range,
    STATE(75), 1,
      sym_case_value,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(41), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [1113] = 7,
    ACTIONS(167), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_number,
    STATE(62), 1,
      sym_case_range,
    STATE(75), 1,
      sym_case_value,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(170), 2,
      anon_sym_END_CASE,
      anon_sym_ELSE,
    STATE(41), 2,
      sym_case,
      aux_sym_case_statement_repeat1,
  [1138] = 6,
    ACTIONS(175), 1,
      anon_sym_END_IF,
    ACTIONS(177), 1,
      anon_sym_ELSIF,
    ACTIONS(179), 1,
      anon_sym_ELSE,
    STATE(61), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [1159] = 6,
    ACTIONS(177), 1,
      anon_sym_ELSIF,
    ACTIONS(179), 1,
      anon_sym_ELSE,
    ACTIONS(181), 1,
      anon_sym_END_IF,
    STATE(67), 1,
      sym_else_clause,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [1180] = 5,
    ACTIONS(7), 1,
      anon_sym_PROGRAM,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_program_definition,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__definition,
      aux_sym_source_file_repeat1,
  [1198] = 4,
    ACTIONS(187), 1,
      anon_sym_ELSIF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(185), 2,
      anon_sym_END_IF,
      anon_sym_ELSE,
    STATE(45), 2,
      sym_elseif_clause,
      aux_sym_if_statement_repeat1,
  [1214] = 5,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 1,
      anon_sym_PROGRAM,
    STATE(58), 1,
      sym_program_definition,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__definition,
      aux_sym_source_file_repeat1,
  [1232] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(51), 1,
      sym__literal,
    STATE(74), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1249] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(51), 1,
      sym__literal,
    STATE(59), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1266] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(199), 4,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
  [1277] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(51), 1,
      sym__literal,
    STATE(77), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1294] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(201), 4,
      anon_sym_THEN,
      anon_sym_DO,
      anon_sym_TO,
      anon_sym_BY,
  [1305] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(51), 1,
      sym__literal,
    STATE(73), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1322] = 5,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      sym_number,
    STATE(51), 1,
      sym__literal,
    STATE(68), 1,
      sym__expression,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1339] = 4,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(80), 1,
      sym_expression_assignment,
    STATE(81), 1,
      sym_for_range,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1353] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(205), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [1362] = 3,
    ACTIONS(207), 1,
      anon_sym_COLON,
    ACTIONS(209), 1,
      anon_sym_DOT_DOT,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1373] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(211), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [1382] = 2,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [1391] = 3,
    ACTIONS(215), 1,
      anon_sym_DO,
    ACTIONS(217), 1,
      anon_sym_BY,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1402] = 2,
    ACTIONS(219), 1,
      anon_sym_END_CASE,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1410] = 2,
    ACTIONS(221), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1418] = 2,
    ACTIONS(207), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1426] = 2,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1434] = 2,
    ACTIONS(181), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1442] = 2,
    ACTIONS(225), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1450] = 2,
    ACTIONS(227), 1,
      anon_sym_OF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1458] = 2,
    ACTIONS(175), 1,
      anon_sym_END_IF,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1466] = 2,
    ACTIONS(229), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1474] = 2,
    ACTIONS(231), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1482] = 2,
    ACTIONS(233), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1490] = 2,
    ACTIONS(235), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1498] = 2,
    ACTIONS(237), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1506] = 2,
    ACTIONS(239), 1,
      anon_sym_THEN,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1514] = 2,
    ACTIONS(241), 1,
      anon_sym_TO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1522] = 2,
    ACTIONS(243), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1530] = 2,
    ACTIONS(245), 1,
      anon_sym_END_CASE,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1538] = 2,
    ACTIONS(247), 1,
      anon_sym_DO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1546] = 2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1554] = 2,
    ACTIONS(251), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1562] = 2,
    ACTIONS(253), 1,
      anon_sym_TO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1570] = 2,
    ACTIONS(255), 1,
      anon_sym_DO,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
  [1578] = 2,
    ACTIONS(257), 1,
      anon_sym_COLON_EQ,
    ACTIONS(3), 2,
      sym_inline_comment,
      sym_block_comment,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 93,
  [SMALL_STATE(5)] = 142,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 220,
  [SMALL_STATE(8)] = 258,
  [SMALL_STATE(9)] = 298,
  [SMALL_STATE(10)] = 334,
  [SMALL_STATE(11)] = 370,
  [SMALL_STATE(12)] = 406,
  [SMALL_STATE(13)] = 442,
  [SMALL_STATE(14)] = 478,
  [SMALL_STATE(15)] = 514,
  [SMALL_STATE(16)] = 550,
  [SMALL_STATE(17)] = 586,
  [SMALL_STATE(18)] = 609,
  [SMALL_STATE(19)] = 632,
  [SMALL_STATE(20)] = 655,
  [SMALL_STATE(21)] = 678,
  [SMALL_STATE(22)] = 701,
  [SMALL_STATE(23)] = 724,
  [SMALL_STATE(24)] = 747,
  [SMALL_STATE(25)] = 770,
  [SMALL_STATE(26)] = 793,
  [SMALL_STATE(27)] = 813,
  [SMALL_STATE(28)] = 833,
  [SMALL_STATE(29)] = 853,
  [SMALL_STATE(30)] = 873,
  [SMALL_STATE(31)] = 893,
  [SMALL_STATE(32)] = 913,
  [SMALL_STATE(33)] = 933,
  [SMALL_STATE(34)] = 953,
  [SMALL_STATE(35)] = 973,
  [SMALL_STATE(36)] = 993,
  [SMALL_STATE(37)] = 1013,
  [SMALL_STATE(38)] = 1033,
  [SMALL_STATE(39)] = 1053,
  [SMALL_STATE(40)] = 1083,
  [SMALL_STATE(41)] = 1113,
  [SMALL_STATE(42)] = 1138,
  [SMALL_STATE(43)] = 1159,
  [SMALL_STATE(44)] = 1180,
  [SMALL_STATE(45)] = 1198,
  [SMALL_STATE(46)] = 1214,
  [SMALL_STATE(47)] = 1232,
  [SMALL_STATE(48)] = 1249,
  [SMALL_STATE(49)] = 1266,
  [SMALL_STATE(50)] = 1277,
  [SMALL_STATE(51)] = 1294,
  [SMALL_STATE(52)] = 1305,
  [SMALL_STATE(53)] = 1322,
  [SMALL_STATE(54)] = 1339,
  [SMALL_STATE(55)] = 1353,
  [SMALL_STATE(56)] = 1362,
  [SMALL_STATE(57)] = 1373,
  [SMALL_STATE(58)] = 1382,
  [SMALL_STATE(59)] = 1391,
  [SMALL_STATE(60)] = 1402,
  [SMALL_STATE(61)] = 1410,
  [SMALL_STATE(62)] = 1418,
  [SMALL_STATE(63)] = 1426,
  [SMALL_STATE(64)] = 1434,
  [SMALL_STATE(65)] = 1442,
  [SMALL_STATE(66)] = 1450,
  [SMALL_STATE(67)] = 1458,
  [SMALL_STATE(68)] = 1466,
  [SMALL_STATE(69)] = 1474,
  [SMALL_STATE(70)] = 1482,
  [SMALL_STATE(71)] = 1490,
  [SMALL_STATE(72)] = 1498,
  [SMALL_STATE(73)] = 1506,
  [SMALL_STATE(74)] = 1514,
  [SMALL_STATE(75)] = 1522,
  [SMALL_STATE(76)] = 1530,
  [SMALL_STATE(77)] = 1538,
  [SMALL_STATE(78)] = 1546,
  [SMALL_STATE(79)] = 1554,
  [SMALL_STATE(80)] = 1562,
  [SMALL_STATE(81)] = 1570,
  [SMALL_STATE(82)] = 1578,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(65),
  [12] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2),
  [14] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(53),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(70),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2), SHIFT_REPEAT(54),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_clause, 4, .production_id = 4),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_case, 3), SHIFT(65),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case, 3),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_clause, 3, .production_id = 4),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_case, 2), SHIFT(65),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_case, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_clause, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_case, 1),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_clause, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 5, .production_id = 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 5, .production_id = 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, .production_id = 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, .production_id = 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, .production_id = 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, .production_id = 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 6, .production_id = 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 6, .production_id = 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, .production_id = 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, .production_id = 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 5),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 5),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 4),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 4),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 4, .production_id = 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 4, .production_id = 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 8, .production_id = 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 8, .production_id = 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_case_statement, 7, .production_id = 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_statement, 7, .production_id = 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__control_statement, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__control_statement, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 6),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 6),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__loop_statement, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__loop_statement, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_case_statement_repeat1, 2), SHIFT_REPEAT(62),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_case_statement_repeat1, 2),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_case_statement_repeat1, 2), SHIFT_REPEAT(56),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_statement_repeat1, 2), SHIFT_REPEAT(52),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 3, .production_id = 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_value, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, .production_id = 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_range, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_range, 3, .production_id = 5),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_assignment, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_range, 5),
  [249] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_text(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
